// const questionList = [
//     {
//         "Are you prscty",
        
//     }
//     "I often try new things just for fun or thrills, even if most people think it is a waste of time",
//     "I usually am confident that everything will go well, even in situations that worry most people",
//     "I often feel that I am the victim of circumstances.",
//     "I can usually accept other people as they are, even when they are very different from me.",
//     "I like a challenge better than easy jobs. ",
//     "Often I feel that my life has little purpose or meaning.",
//     "I like to help find a solution to problems so that everyone comes out ahead",
//     "I am usually eager to get going on any job I have to do.",
//     "I often feel tense and worried in unfamiliar situations, even when others feel there is little to worry about.",
//     "I often do things based on how I feel at the moment without thinking about how they were done in the past.",
//     "I usually do things my own way - rather than giving in to the wishes of other people",
//     "I often feel a strong sense of unity with all the things around me.",
//     "If something doesn't work as I expected, I am more likely to quit than to keep going for a long time.",
//     "I am much more reserved and controlled than most people",
//     "I like to discuss my experiences and feelings openly with friends instead of keeping them to myself",
//     "I have less energy and get tired more quickly than most people.",
//     "I seldom feel free to choose what I want to do.",
//     "I don't seem to understand most people very well",
//     "I often avoid meeting strangers because I lack confidence with people I do not know",
//     "I like to please other people as much as I can.",
//     "I often wish that I was smarter than everyone else",
//     "No job is too hard for me to do my best.",
//     "I often wait for someone else to provide a solution to my problems.",
//     "I often spend money until I run out of cash or get into debt from using too much credit.",
//     "Often I have unexpected flashes of insight or understanding while relaxing.",
//     "I don't care very much whether other people like me or the way I do things.",
//     "I usually try to get just what I want for myself because it is not possible to satisfy everyone anyway.",
//     "I have no patience with people who don't accept my views",
//     "I sometimes feel so connected to nature that everything seems to be part of one living process.",
//     "I often break rules and regulations when I think I can get away with it",
//     "I am more sentimental than most people.",
//     "I think that most things that are called miracles are just chance",
//     "When someone hurts me in any way, I usually try to get even.",
//     "My actions are determined largely by influences outside my control.",
//     "Each day I try to take another step toward my goals.",
//     "Please click on Mostly or probably true this is a validity item",
//     "I am a very ambitious person",
//     "I usually stay calm and secure in situations that most people would find physically dangerous",
//     "I do not think it is smart to help weak people who cannot help themselves.",
//     "I cannot have any peace of mind if I treat other people unfairly, even if they are unfair to me.",
//     "I often follow my instincts, hunches, or intuition without thinking through all the details.",
//     "Sometimes I have felt like I was part of something with no limits or boundaries in time and space.",
//     "My friends find it hard to know my feelings because I seldom tell them about my private.",
//     "I like it when people can do whatever they want without strict rules and regulations",
//     "When I fail at something, I become even more determined to do a better job",
//     "Usually I am more worried than most people that something might go wrong in the future.",
//     "I usually think about all the facts in detail before I make a decision.",
//     "It is extremely difficult for me to adjust to changes in my usual way of doing things because I get so tense, tired, or worried.",
//     "Other people control me too much.",
//     "I like to be of service to others.",
//     "I am usually able to get other people to believe me, even when I know that what I am saying is exaggerated or untrue.",
//     "Sometimes I have felt my life was being directed by a spiritual force greater than any human being",
//     "When nothing new is happening, I usually start looking for something that is thrilling",
//     "I am strongly moved by sentimental appeals (like when asked to help crippled children).",
//     "I am usually so determined that I continued to work long after other people have given up",
//     "I have had moments of great joy in which I suddenly had a clear, deep feeling of oneness with all that exists.",
//     "I feel very confident and sure of myself in almost all social situations.",
//     "I often cannot deal with problems because I just don't know what to do.",
//     "I prefer spending money rather than saving it.",
//     "I have often been called an eager beaver because of my enthusiasm for hard work."
// ];

// module.exports = questionList;
